param(
    [string]$MusicDirectory = (Join-Path $PSScriptRoot '../music'),
    [string]$OutputDirectory = (Join-Path $PSScriptRoot '../output')
)
$ErrorActionPreference = 'Stop'
$utf8 = New-Object System.Text.UTF8Encoding($false)
$periods = @('morning', 'noon', 'evening', 'midnight')
$inputs = @{}
$total = 0
# Validate every playlist before creating any output.
foreach ($period in $periods) {
    $folder = Join-Path $MusicDirectory $period
    if (-not (Test-Path -LiteralPath $folder -PathType Container)) {
        throw "Music folder missing: $folder"
    }
    $files = @(Get-ChildItem -LiteralPath $folder -File -Filter '*.ogg' | Sort-Object Name)
    if ($files.Count -gt 10) { throw "$period has $($files.Count) tracks; the limit is 10." }
    foreach ($file in $files) {
        $stream = [System.IO.File]::OpenRead($file.FullName)
        try {
            $header = New-Object byte[] 128
            $length = $stream.Read($header, 0, $header.Length)
            $text = [System.Text.Encoding]::ASCII.GetString($header, 0, $length)
            if (-not $text.StartsWith('OggS') -or -not $text.Contains('vorbis')) {
                throw "Not an Ogg Vorbis file: $($file.FullName). Renaming MP3/Opus to .ogg does not convert it."
            }
        } finally { $stream.Dispose() }
    }
    $inputs[$period] = $files
    $total += $files.Count
}
if ($total -eq 0) { throw 'No Ogg Vorbis tracks found. Add music under music/morning, noon, evening or midnight first.' }

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null
# A unique staging folder keeps old tracks out of rebuilt packs without deleting user files.
$stage = Join-Path $OutputDirectory ('staging-' + [guid]::NewGuid().ToString('N'))
$assetRoot = Join-Path $stage 'assets/world_music'
New-Item -ItemType Directory -Path $assetRoot -Force | Out-Null
$sounds = [ordered]@{}
$mapping = New-Object System.Collections.Generic.List[string]
$config = New-Object System.Collections.Generic.List[string]
$config.Add('# Generated by World Music. Copy this file to your game config folder while the game is closed.')
$config.Add('enabled = true')
$config.Add('overworldOnly = true')
$config.Add('emptyUsesVanilla = true')
foreach ($period in $periods) {
    $dest = Join-Path $assetRoot ('sounds/' + $period)
    New-Item -ItemType Directory -Path $dest -Force | Out-Null
    $ids = @()
    $index = 0
    foreach ($file in $inputs[$period]) {
        $index++
        $eventName = "${period}_${index}"
        Copy-Item -LiteralPath $file.FullName -Destination (Join-Path $dest "$index.ogg")
        $sounds[$eventName] = @{ sounds = @(@{ name = "world_music:$period/$index"; stream = $true }) }
        $ids += '"world_music:' + $eventName + '"'
        $mapping.Add("world_music:$eventName = $($file.Name)")
    }
    $config.Add($period + ' = [' + ($ids -join ', ') + ']')
}
$metadata = @{ pack = @{ description = 'World Music - custom time-of-day playlists'; min_format = 84; max_format = 84 } }
[IO.File]::WriteAllText((Join-Path $stage 'pack.mcmeta'), ($metadata | ConvertTo-Json -Depth 5), $utf8)
[IO.File]::WriteAllText((Join-Path $assetRoot 'sounds.json'), (ConvertTo-Json -InputObject $sounds -Depth 8), $utf8)
[IO.File]::WriteAllLines((Join-Path $OutputDirectory 'world_music-client.toml'), $config, $utf8)
[IO.File]::WriteAllLines((Join-Path $OutputDirectory 'track-mapping.txt'), $mapping, $utf8)
$zip = Join-Path $OutputDirectory 'WorldMusicPack.zip'
Compress-Archive -Path (Join-Path $stage '*') -DestinationPath $zip -Force
Write-Host "Created $zip with $total tracks."
Write-Host 'Put the ZIP in your game resourcepacks folder and enable it in game.'
Write-Host 'Copy output/world_music-client.toml to your game config folder while the game is closed.'
